// src/components/YO.tsx
import { createSignal } from "solid-js"

export default function YO() {
  const [year, setYear] = createSignal(new Date().getFullYear())
  const delta = () => year() - 2005

  return (
    <p>
      西暦
      <input
        type="number"
        value={year()}
        onInput={e => setYear(Number(e.currentTarget.value))}
        style={{
          width: "6em",
          margin: "0 .3em",
        }}
      />
      年において，山Dは
      {delta() < 0 ? (
        <>まだ生まれていません。</>
      ) : (
        <>
          <strong>{delta()}</strong>歳です。
        </>
      )}
      {delta() >= 200 && <>おそらく死んでいます。</>}
    </p>
  )
}

// src/components/YO.svelte
<script lang="ts">
  let value = new Date().getFullYear()
  $: delta = value - 2005
</script>

<p>
  西暦<input type="number" bind:value />年において，山Dは{#if delta < 0}
    まだ生まれていません。{:else}<strong>{delta}</strong>歳です。{/if}{#if delta >= 200}
    おそらく死んでいます。
  {/if}
</p>

<style>
  input {
    width: 6em;
    margin: 0 0.3em;
  }
</style>
